external_components:
  - source:
      type: local
      path: components

substitutions:
  name: lora-gateway
  logger_level: DEBUG
  friendly_name: LoRa Gateway
  lora_module_id: sx126x_module
  lora_pa_power: 10
  lora_bandwidth: 125_0kHz
  lora_frequency: 917500000 # 917.5 MHz
  lora_spreading_factor: 7
  lora_coding_rate: CR_4_5

packages:
  # - !include includes/debug.yaml
  - !include includes/common.yaml
  - !include includes/ha-time.yaml
  - !include includes/diagnostic-sensors.yaml
  - !include includes/heltec-lora.yaml

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  area: Indoor

esp32:
  board: heltec_wifi_lora_32_V3
  variant: esp32s3
  cpu_frequency: 160mhz
  flash_size: 8mb
  framework:
    type: arduino
    version: "3.3.2"

wifi:
  networks:
    - ssid: !secret outdoor_wifi_ssid
      password: !secret wifi_password
    - ssid: !secret outdoor_wifi_ssid_2
      password: !secret wifi_password
  power_save_mode: NONE
  output_power: 20dB

  # fallback hotspot if WiFi fails
  ap:
    ssid: ${friendly_name} Fallback
    password: !secret hotspot_password

web_server:
  port: 80

lora_gateway:
  id: lora_gw
  sx126x_id: ${lora_module_id}
  address: 0x01
  auth_key: !secret lora_auth_key
  response_timeout: 2s
  poll_interval: 10s
  time_id: ha_time
  time_sync_interval: 60s
  send_ack: false
  stale_sensor_behavior: keep
  remote_nodes:
    - id: test_node_1
      address: 0x02
      name: Test Node 1

text_sensor:
  - platform: lora_gateway
    lora_gateway_id: lora_gw
    timeout_list:
      name: "Gateway Timeout List"
    last_heard_list:
      name: "Gateway Last Heard"
    signal_quality_list:
      name: "Gateway Signal Quality"

sensor:
  - platform: heltec_battery_sensor
    update_interval: 5s
    battery_voltage:
      id: gateway_battery_voltage
      name: Gateway Battery Voltage
      entity_category: diagnostic
      device_class: voltage
      state_class: measurement
      accuracy_decimals: 2
      filters:
        - calibrate_linear:
            datapoints:
              - 3.67 -> 3.58
              - 3.97 -> 3.87
              - 4.08 -> 3.96
              - 4.15 -> 4.01
              - 4.33 -> 4.20
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10
    battery_level:
      id: battery_level
      name: Gateway Battery Level
      entity_category: diagnostic
      filters:
        - clamp:
            min_value: 0.0
            max_value: 100.0
        - sliding_window_moving_average:
            window_size: 12
            send_every: 12
