#!/bin/bash

# Loads secrete.yaml contents from 1Password and creates/overwrites local secrets.yaml with it.
# Requires jq to be installed

SECRETS_NOTE_TITLE="${1:-"coop-deville esphome secrets"}"
SECRETS_JSON="$(op item get "${SECRETS_NOTE_TITLE}" --fields notesPlain --format json | jq -r .value)"
SECRETS_COUNT="$(echo "$SECRETS_JSON" | grep -Ev '^$|^#' | wc -l | sed 's/^[[:space:]]*//')"

echo "$SECRETS_JSON" > secrets.yaml
echo "Successfully populated secrets.yaml with ${SECRETS_COUNT} secrets from 1Password"

